version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      - JAVA_OPTIONS: "-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError"

  general-executor:
    docker:
      - environment:
          TERM: dumb
        image: 'cibuilds/base:latest'
    resource_class: small

aliases:
  - &create_keystore
    run:
      name: Create ks.jks
      command: echo $RELEASE_KEYSTORE_BASE64 | base64 -d > $releaseKeyStore
  - &create_keystore_properties
    run:
      name: Create keystore.properties
      command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' $releaseKeyAlias $releaseKeyPassword $releaseKeyStore $releaseStorePassword > keystore.properties
  - &perm_gradle
    run:
      name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      command: sudo chmod +x ./gradlew
  - &assemble
    run:
      name: Assemble Project
      command: ./gradlew assembleRelease
  - &unit_tests
    run:
      name: Run Unit Tests
      command: ./gradlew :app:testReleaseUnitTest
  #  Placeholder deployment task
  - &deploy_apk
    run:
      name: Deploy Release Artifact
      command: echo "Deploy release for distribution"
  - &work_storing_artifacts
    store_artifacts:
      path: app/build/reports
      destination: reports
  - &work_storing_test_resuts
    store_test_results:
      path: app/build/test-results

slack-aliases:
  - &slack_channel_webhook
      ${CIRCLE_SLACK_WEBHOOK}
  - &notify_slack_for_approval
    slack/notify:
      color: '#400080'
      message: |
        [${CIRCLE_USERNAME}] Please check and approve Jobs to manually deploy the releases.
        https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
      webhook: *slack_channel_webhook

jobs:

  build:
    executor: android-executor
    steps:
      - checkout
      - *create_keystore
      - *create_keystore_properties
      - *perm_gradle
      - *assemble
      - *unit_tests
      - *work_storing_artifacts
      - *work_storing_test_resuts

  slack-approval-link:
    executor: general-executor
    steps:
      - *notify_slack_for_approval

  deploy:
    executor: android-executor
    steps:
      - checkout
      - *create_keystore
      - *create_keystore_properties
      - *perm_gradle
      - *assemble
      - *deploy_apk

orbs:
  slack: circleci/slack@3.4.1

workflows:
  version: 2.1

  build-workflow:
    jobs:
      - build

      - slack-approval-link:
          requires:
            - build

      - pending-deployment:
          type: approval
          requires:
            - build

      - deploy:
          requires:
            - pending-deployment